server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:biblioteca;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 🔹 Garante que o data.sql rode DEPOIS do Hibernate criar o schema
    defer-datasource-initialization: true

  # 🔹 Força execução de data.sql mesmo sem "schema.sql"
  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /swagger-ui.html
